---
title: "dev"
format: 
  html: 
   df-print: paged
execute: 
  cache: true
---

```{r}
#| label: setup
#| force: true
#| message: false
library(data.table)
library(dplyr)
library(dbplyr)
library(biomaRt)
```

```{r}
#| label: load-data
overlap_stopgain <- fread("processed_data/overlap_stopgain_processed.csv")

```


-   biomaRt requires dbplyr version 2.3.4 (needs manual downgrad) or alternatively BiocFileCache 3.18 (needs r 4.3)
-   Using dbplyr downgrade for now


```{r}
#| label: initialise-biomaRt

listEnsembl()
ensembl <- useEnsembl("genes")
# Version of used dataset:
searchDatasets(ensembl, pattern = "hsapiens")
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")


searchFilters(ensembl, pattern = "hgnc")
bm_filter = "ensembl_gene_id"


listAttributes(ensembl)
searchAttributes(ensembl, pattern = "go")

#TODO find correct attributes and continue with query 
bm_attributes <- c("ensembl_gene_id","hgnc_symbol","go_id", "goslim_goa_description", "interpro_description")

test_set <- overlap_stopgain[1:10, c(1:4,11,12)]


getBM(attributes = bm_attributes,
      filters = bm_filter,
      values = test_set$GeneID,
      mart = ensembl)

library(dplyr)

overlap_stopgain |> group_by(GeneID) |> 
  slice_max(order_by = PHRED, n = 1) |>
  dplyr::select(all_of(c("GeneID", "PHRED"))) |>
  fwrite("processed_data/genelist.csv")


```


